### ISSUE TITLE
Error when using the pretrained model

### ISSUE THREAD

**Issue by LuChengTHU** [yang-song/score_flow#3]
Dear authors,

I'm using the pretrained model "cifar10_deep_vp_likelihood_iw_flip", and I get this error when restoring the checkpoint:

flax.errors.ScopeParamShapeError: Inconsistent shapes between value and initializer for parameter "scale" in "/ResnetBlockBigGANpp_0/GroupNorm_0": (1, 1, 1, 128), (128,). (https://flax.readthedocs.io/en/latest/flax.errors.html#flax.errors.ScopeParamShapeError)

What should I do? Thank you!

**Comment by yang-song** [comment]
Are you sure you are using the same `flax` and `jax` version as specified in `requirements.txt`?

**Comment by LuChengTHU** [comment]
Thanks for your fast reply!

I cannot find the correct version of flax, because the URL https://github.com/google/flax.git@8b2e56e93602ff9fcd62647f28b8145e0e0c10a8 in the requirements reports "not found".

**Comment by yang-song** [comment]
You probably need to download the flax source code at the right version, and use `pip install -e` to install. The error you observed is likely due to upgraded flax using a different protocol to store checkpoints

**Comment by yang-song** [comment]
That's interesting, I probably used the nightly built of flax at some moment. Could you try downloading the flax github repo, checking into the node 8b2e56e93602ff9fcd62647f28b8145e0e0c10a8, and installing with `pip install -e` there?

**Comment by LuChengTHU** [comment]
Thanks, it works. And It seems that flax==0.3.3 also works, FYI.
